### ISSUE TITLE
卸载后看不到效果

### ISSUE THREAD

**Issue by leizhipeng01** [DonnYep/QuarkAsset#1]
UnloadAsset，我调用后并没有想象中卸载掉资源
UnloadAssetBundle这方法参数为TRUE 释放AssetBundle文件内存镜像同时销毁所有已经Load的Assets内存对象?
比较菜，我看这个框架是学习用的，请大佬解惑

**Comment by DonnYep** [comment]
可以提供一下你使用的操作吗，比如加载模式，加载卸载的aip等。

**Comment by leizhipeng01** [comment]
void Update()
    {
        //我只是在试着用，源码迷迷糊糊看个大概，很可能不是bug是我不会用法
        if (Input.GetKeyDown(KeyCode.Q))
        {
            resourceManager.LoadAssetAsync<GameObject>("Cube", (obj) =>
            {
                if (obj != null)
                {
                    Debug.LogError("Load suc");
                    GameObject go = obj as GameObject;

                    GameObject entiy = Instantiate(go);

                    QuarkAssetObjectInfo quarkAssetObjectInfo = new QuarkAssetObjectInfo();
                    resourceManager.GetInfo<GameObject>("Cube", out quarkAssetObjectInfo);
                    Debug.LogError(quarkAssetObjectInfo.AssetName + ": " + quarkAssetObjectInfo.ReferenceCount);
                }
            });
        }

        if (Input.GetKeyDown(KeyCode.W))
        {
            //我觉得应该是卸载内存中的Cube和实例化的实体
            resourceManager.UnloadAsset("Cube");
            QuarkAssetObjectInfo quarkAssetObjectInfo = new QuarkAssetObjectInfo();
            resourceManager.GetInfo<GameObject>("Cube", out quarkAssetObjectInfo);
            Debug.LogError(quarkAssetObjectInfo.AssetName + ": " + quarkAssetObjectInfo.ReferenceCount);
        }

        if (Input.GetKeyDown(KeyCode.E))
        {
            //等同AssetBundle.Unload(false)
            resourceManager.UnloadAssetBundle("Cube", false);
            QuarkAssetObjectInfo quarkAssetObjectInfo = new QuarkAssetObjectInfo();
            bool info = resourceManager.GetInfo<GameObject>("Cube", out quarkAssetObjectInfo);
            if (info)
            {
                Debug.LogError(quarkAssetObjectInfo.AssetName + ": " + quarkAssetObjectInfo.ReferenceCount);
            }
            else
            {
                Debug.LogError("False");
            }
        }

        if (Input.GetKeyDown(KeyCode.R))
        {
            //等同AssetBundle.Unload(true)
            resourceManager.UnloadAssetBundle("Cube", true);
            QuarkAssetObjectInfo quarkAssetObjectInfo = new QuarkAssetObjectInfo();
            bool info = resourceManager.GetInfo<GameObject>("Cube", out quarkAssetObjectInfo);
            if (info)
            {
                Debug.LogError(quarkAssetObjectInfo.AssetName + ": " + quarkAssetObjectInfo.ReferenceCount);
            }
            else
            {
                Debug.LogError("False");
            }
        }
    }

**Comment by leizhipeng01** [comment]
或者是这样用法       UnloadAsset ab，内存里的资源自己去删除？
  FrameworkEntry.Instance.GetManager<ResourceManager>().UnloadAsset(uiFormAsset);
        Destroy((Object)uiFormInstance);

**Comment by DonnYep** [comment]
我尝试了你的调用的方式，确认了这是一处不合理的地方。资源卸载令引用计数归零，bundle确实被卸载了，但是已经生成的资源未被销毁。现已将AssetBundle.Unload(unloadAllLoadedObjects)中的unloadAllLoadedObjects参数默认设置为了true，并更新提交指upm分支。
十分感谢你的反馈，有任何问题疑问，或者有需要的功能支持，都请issue给我，我会尽快回应。
