### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by leizhipeng01** [DonnYep/QuarkAsset#3]
![image](https://user-images.githubusercontent.com/101231025/206336586-8c56979b-f755-47f0-b0b3-1c127edeeb28.png)
整体功能非常完善了。开发项目打包资源很多，会非常乱，可以把右侧显示为某一个Bundle的资源内容会更好点。

**Comment by DonnYep** [comment]
升级quark editor在计划之中，包含bundle展示的这部分。预计会与这个:https://github.com/DonnYep/CosmosFramework/blob/v1.3/Docs/RESOURCE_EDITOR.md 比较接近，但是各有侧重。

**Comment by leizhipeng01** [comment]
我看过您的框架纯粹是不太忙学下大佬的思路，因为文档比较少，所以我还没有用过这个框架做项目。不过我看您这个和gameframework也有一点相似的地方，未来一定是一个优秀的框架。谢谢大佬的开源

**Comment by DonnYep** [comment]
感谢你的认可。我开源的几个仓库文档确实有所不足，近期会补充一波文档，以帮助大家使用。CF借鉴学习了不少优秀的开源项目，其中就包含gf，因此与gf有所相似。希望我的代码能够帮助到你，也感谢你对我代码的关注与支持。
