### ISSUE TITLE
场景加载报错

### ISSUE THREAD

**Issue by leizhipeng01** [DonnYep/QuarkAsset#4]
LoadSceneAsync(string sceneName, Action<float> progress, Action callback); 
 参数：(sceneName, progress, callback, true);
UnloadAllSceneAsync(Action<float> progress, Action callback);
先调用LoadScene,加载完毕后调用UnloadAllSceneAsync会报错。foreach循环增删的问题，但是我看代码觉得写的没问题。
辛苦您看看
报错：Assets/QuarkAsset/Runtime/Loader/QuarkAssetDatabaseLoader.cs:320--->Collection was modified; enumeration operation may not execute.

**Comment by leizhipeng01** [comment]
/// <summary>
        /// 当场景被卸载；
        /// </summary>
        void OnSceneUnloaded(Scene scene)
        {
            var sceneName = scene.name;
            if (loadSceneList.Remove(sceneName))
            {
                var hasObject = GetSceneObject(sceneName, out var quarkObject);
                if (hasObject)
                    OnResourceObjectUnload(quarkObject);
            }
            loadedSceneDict.Remove(sceneName);
        }

测试应该是和这个方法起冲突了。我把 if (loadSceneList.Remove(sceneName))这个地方

**Comment by DonnYep** [comment]
十分感谢反馈这个bug，现已提交修复。虽然这个API叫做UnloadAllSceneAsync，但是由于unity的机制，场景中必须存在一个场景，因此无法卸载所有被quark加载的场景，（若所有场景都是被quark加载的话）。
