### ISSUE TITLE
卸载报空错误

### ISSUE THREAD

**Issue by leizhipeng01** [DonnYep/QuarkAsset#5]
QuarkAssetBundleLoader  提前自己卸载部分ab，在关闭程序卸载所有ab,此处报空 。 ？.NULL检查运算符好像没有起作用！
![image](https://user-images.githubusercontent.com/101231025/208012355-81ed533e-eaeb-4c33-8b23-e302db60cfe3.png)

**Comment by DonnYep** [comment]
感谢提出这个问题，这是由于assetbundle卸载后未置空导致的，已在提交的重构代码中修复。
