### ISSUE TITLE
在循环中使用 QuarkResources.LoadAssetAsyn 好像不能正确的加载的数据.

### ISSUE THREAD

**Issue by XiaoFanJx2** [DonnYep/QuarkAsset#6]
我在想在加载场景中使用 LoadAssetAsync 先加载一些数据到内存里 格式类似下方的格式  但是很奇怪 LoadAssetAsync 的回调函数 onComplete  只会获得 AtlasType枚举 中的其中一个数据 (应该是枚举元素个数的数据)  而且有时也会报错 :
**The AssetBundle 'StreamingAssets\assets_2dassest_spriteatlas' can't be loaded because another AssetBundle with the same files is already loaded.**

foreach (AtlasType atlasType in Enum.GetValues(typeof(AtlasType)))//示例代码
{
            QuarkResources.LoadAssetAsync<T>(path, onComplete);
}

**Comment by XiaoFanJx2** [comment]
已经解决 我没有在  AssetDatasetTab 下添加  spriteatlasv2 后缀导致最新的 图集加载不到

**Comment by DonnYep** [comment]
@XiaoFanJx2 我使用与你相同的方式在ab模式下异步加载资源，显示确实会出现ab包体的报错。感谢你能指出这个bug，我已经在最新的提交中修复了这个问题。
