### ISSUE TITLE
不太明白这个路径为什么不能拖到编辑器窗口

### ISSUE THREAD

**Issue by foreversos** [DonnYep/QuarkAsset#7]
[QUARK-ERROR]-->> Cannot mark assets and scenes in one AssetBundle. AssetBundle name is Assets/SubGame/Game_2D
UnityEngine.Debug:LogError (object)
Quark.QuarkUtility:LogError (object) (at ./Library/PackageCache/com.quarkasset@2fc4b79a91/Runtime/Utility/QuarkUtility.cs:186)
Quark.Editor.QuarkBundleSearchLabel:DrawDragRect () (at ./Library/PackageCache/com.quarkasset@2fc4b79a91/Editor/QuarkWindowTab/QuarkAssetDatabaseTab/QuarkBundleSearchLabel.cs:93)
Quark.Editor.QuarkBundleSearchLabel:OnGUI (UnityEngine.Rect) (at ./Library/PackageCache/com.quarkasset@2fc4b79a91/Editor/QuarkWindowTab/QuarkAssetDatabaseTab/QuarkBundleSearchLabel.cs:50)
Quark.Editor.QuarkAssetDatabaseTab:OnGUI (UnityEngine.Rect) (at ./Library/PackageCache/com.quarkasset@2fc4b79a91/Editor/QuarkWindowTab/QuarkAssetDatabaseTab/QuarkAssetDatabaseTab.cs:124)
Quark.Editor.QuarkAssetWindow:OnGUI () (at ./Library/PackageCache/com.quarkasset@2fc4b79a91/Editor/QuarkAssetWindow.cs:113)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

看起来没也什么特殊字符,请教下

**Comment by DonnYep** [comment]
unity的scene文件ab文件打包不允许包含其他类型的文件。即一个ab文件中，若存在scene文件，则只允许存在scene文件，否则unity构建ab时无法成功。因此在quark中配置ab时，做了检测是否同时存在scene与其他文件的操作。

**Comment by foreversos** [comment]
OK.明白了,单独放个文件就好了
